export const ContentSolution = [
    {
        id:1,
        Name:'FortiClient Installation',
        Description:'This solution helps to install FortiClient',
        username:53545,
        ipaddress:'78.123.123.87',
        systemId:34536556,
        location:"delhi",
        version:3.3,
        serialNumber: "1N12150C11",
    },
    {
        id:2,
        Name:'Free up disk space',
        Description:'This solution elps to free up C Drvie disk space by removing temporary and unused files',
        username:67615,
        systemId:75654387,
        ipaddress:'78.123.123.87',
        location:"noida",
        version:3.3,
        serialNumber: "1N122076G",
    },
    {
        id:3,
        Name:'Speed up your machine',
        Description:'This solution helps to speed up your machine by freeing up disk space and various system optimiazaiton operations',
        username:136710,
        ipaddress:'78.123.123.87',
        systemId:567866891,
        location:"mumbai",
        version:3.3,
        serialNumber: "INA512P49W",
    },
    {
        id:4,
        Name:'MS Excel hangs when tries to format any cell',
        Description:'This solution helps to resolve Excel hangs when tries to format any cell',
        username:53566,
        systemId:9867578765,
        ipaddress:'78.123.123.87',
        location:"chennai",
        version:3.3,
        serialNumber: "6X9QPQ1",
    },
]